const sampleListings = [
  {
    title: "Serene Mountain Cabin",
    description: "A peaceful cabin retreat in the mountains, perfect for escaping the city.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1380&auto=format&fit=crop" },
    price: 2500,
    location: "Manali",
    country: "India",
    geometry: { type: "Point", coordinates: [77.1887, 32.2432] },
    features: ["mountains", "countryside"],
  },
  {
    title: "Luxury Beachfront Villa",
    description: "Stunning villa with a private pool and direct access to the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1374&auto=format&fit=crop" },
    price: 8000,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [73.818, 15.4909] },
    features: ["beachfront", "amazing_pools", "luxe"],
  },
  {
    title: "Urban Loft in Mumbai",
    description: "Chic and modern loft in the heart of Mumbai's trendiest district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop" },
    price: 4500,
    location: "Mumbai",
    country: "India",
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    features: ["iconic_cities"],
  },
  {
    title: "Historic Palace in Jaipur",
    description: "Live like royalty in this beautifully restored heritage palace.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1470&auto=format&fit=crop" },
    price: 12000,
    location: "Jaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
    features: ["castles", "luxe"],
  },
  {
    title: "Riverside Cottage in Kerala",
    description: "Charming cottage on the banks of the serene Kerala backwaters.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=1470&auto=format&fit=crop" },
    price: 3000,
    location: "Alleppey",
    country: "India",
    geometry: { type: "Point", coordinates: [76.3388, 9.4981] },
    features: ["boats", "countryside"],
  },
  {
    title: "Desert Camp in Jaisalmer",
    description: "Experience a magical night under the stars in a luxury desert camp.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=1374&auto=format&fit=crop" },
    price: 5000,
    location: "Jaisalmer",
    country: "India",
    geometry: { type: "Point", coordinates: [70.9083, 26.9157] },
    features: ["off_the_grid"],
  },
  {
    title: "Tea Plantation Bungalow",
    description: "Stay amidst lush tea gardens in a colonial-era bungalow.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1400&auto=format&fit=crop" },
    price: 6000,
    location: "Munnar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    features: ["farms", "countryside"],
  },
  {
    title: "Himalayan Homestay",
    description: "A cozy and authentic homestay with breathtaking views of the Himalayas.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1470&auto=format&fit=crop" },
    price: 2000,
    location: "Shimla",
    country: "India",
    geometry: { type: "Point", coordinates: [77.1734, 31.1048] },
    features: ["mountains", "private_rooms"],
  },
  {
    title: "Modern Apartment in Bangalore",
    description: "A sleek and comfortable apartment in the tech hub of Bangalore.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=1470&auto=format&fit=crop" },
    price: 3500,
    location: "Bangalore",
    country: "India",
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    features: ["iconic_cities"],
  },
  {
    title: "Quaint Cottage in Ooty",
    description: "A charming English-style cottage in the hill station of Ooty.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1374&auto=format&fit=crop" },
    price: 4000,
    location: "Ooty",
    country: "India",
    geometry: { type: "Point", coordinates: [76.705, 11.4102] },
    features: ["mountains", "cabins"],
  },
  {
    title: "Treehouse in Wayanad",
    description: "Unique and adventurous stay in a treehouse overlooking the forest.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1470&auto=format&fit=crop" },
    price: 5500,
    location: "Wayanad",
    country: "India",
    geometry: { type: "Point", coordinates: [76.132, 11.6854] },
    features: ["off_the_grid", "tiny_homes"],
  },
  {
    title: "Lake Palace in Udaipur",
    description: "An ethereal and romantic experience in a palace on Lake Pichola.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1471&auto=format&fit=crop" },
    price: 15000,
    location: "Udaipur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.6822, 24.5765] },
    features: ["luxe", "castles", "trending"],
  },
  {
    title: "Spiritual Retreat in Rishikesh",
    description: "Find your inner peace at this serene retreat by the Ganges.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1470&auto=format&fit=crop" },
    price: 2800,
    location: "Rishikesh",
    country: "India",
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
    features: ["mountains"],
  },
  {
    title: "French Quarter Home, Pondicherry",
    description: "Charming colonial home in the picturesque French Quarter.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1374&auto=format&fit=crop" },
    price: 4200,
    location: "Pondicherry",
    country: "India",
    geometry: { type: "Point", coordinates: [79.8317, 11.9338] },
    features: ["iconic_cities"],
  },
  {
    title: "Wildlife Lodge near Corbett",
    description: "Stay on the edge of the famous Corbett National Park.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1528913793388-a346c21a4f2d?q=80&w=1470&auto=format&fit=crop" },
    price: 6500,
    location: "Ramnagar",
    country: "India",
    geometry: { type: "Point", coordinates: [79.1235, 29.3919] },
    features: ["countryside", "off_the_grid"],
  },
  {
    title: "Artistic Studio in Kolkata",
    description: "A vibrant and creative studio in the cultural heart of Kolkata.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1380&auto=format&fit=crop" },
    price: 3200,
    location: "Kolkata",
    country: "India",
    geometry: { type: "Point", coordinates: [88.3639, 22.5726] },
    features: ["iconic_cities"],
  },
  {
    title: "Ski Chalet in Gulmarg",
    description: "Cozy chalet perfect for a winter ski trip in the Himalayas.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587061949409-02df41d545a3?q=80&w=1470&auto=format&fit=crop" },
    price: 7500,
    location: "Gulmarg",
    country: "India",
    geometry: { type: "Point", coordinates: [74.385, 34.0483] },
    features: ["mountains", "arctic", "cabins"],
  },
  {
    title: "Houseboat on Dal Lake",
    description: "A traditional and luxurious houseboat experience in Srinagar.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1617462243993-61788a87c1f1?q=80&w=1470&auto=format&fit=crop" },
    price: 4800,
    location: "Srinagar",
    country: "India",
    geometry: { type: "Point", coordinates: [74.826, 34.0837] },
    features: ["boats", "trending"],
  },
  {
    title: "Coffee Estate Homestay, Coorg",
    description: "Wake up to the aroma of coffee in this beautiful estate homestay.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1617462243993-61788a8b7c1f1?q=80&w=1470&auto=format&fit=crop" },
    price: 3800,
    location: "Coorg",
    country: "India",
    geometry: { type: "Point", coordinates: [75.7397, 12.4245] },
    features: ["farms", "countryside"],
  },
  {
    title: "Rock Cut Cave House, Hampi",
    description: "A unique stay in a house carved from the rocks of Hampi.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1599640842225-85d111c60e6b?q=80&w=1374&auto=format&fit=crop" },
    price: 2200,
    location: "Hampi",
    country: "India",
    geometry: { type: "Point", coordinates: [76.46, 15.335] },
    features: ["tiny_homes", "off_the_grid"],
  },
  {
    title: "Penthouse with City Views, Delhi",
    description: "Luxury penthouse with a rooftop terrace overlooking the Delhi skyline.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?q=80&w=1470&auto=format&fit=crop" },
    price: 9000,
    location: "Delhi",
    country: "India",
    geometry: { type: "Point", coordinates: [77.209, 28.6139] },
    features: ["iconic_cities", "luxe", "amazing_pools"],
  },
  {
    title: "Beach Hut in Gokarna",
    description: "Simple and rustic beach hut for the ultimate laid-back vacation.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=1374&auto=format&fit=crop" },
    price: 1500,
    location: "Gokarna",
    country: "India",
    geometry: { type: "Point", coordinates: [74.318, 14.5479] },
    features: ["beachfront", "tiny_homes"],
  },
  {
    title: "Vineyard Stay in Nashik",
    description: "Relaxing stay at a vineyard with wine tasting sessions.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1470&auto=format&fit=crop" },
    price: 5200,
    location: "Nashik",
    country: "India",
    geometry: { type: "Point", coordinates: [73.7898, 19.9975] },
    features: ["farms", "countryside"],
  },
  {
    title: "Monastery View Room, Ladakh",
    description: "A simple room with a stunning view of a mountain monastery.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1573496377443-31621366a7a0?q=80&w=1469&auto=format&fit=crop" },
    price: 2800,
    location: "Leh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.584, 34.1526] },
    features: ["mountains", "private_rooms"],
  },
  {
    title: "Island Villa, Andaman",
    description: "Exclusive villa on a secluded island in the Andamans.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1570214476695-18bd59728a7a?q=80&w=1374&auto=format&fit=crop" },
    price: 11000,
    location: "Havelock Island",
    country: "India",
    geometry: { type: "Point", coordinates: [92.985, 11.972] },
    features: ["beachfront", "luxe", "amazing_pools"],
  },
  {
    title: "Royal Tent in Pushkar",
    description: "Luxurious tented accommodation during the Pushkar Camel Fair.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1599793333466-a5b5b7571112?q=80&w=1470&auto=format&fit=crop" },
    price: 6800,
    location: "Pushkar",
    country: "India",
    geometry: { type: "Point", coordinates: [74.553, 26.491] },
    features: ["castles", "trending"],
  },
  {
    title: "Golf Course Villa, Gurgaon",
    description: "A modern villa overlooking a lush green golf course.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1470&auto=format&fit=crop" },
    price: 8500,
    location: "Gurgaon",
    country: "India",
    geometry: { type: "Point", coordinates: [77.0266, 28.4595] },
    features: ["luxe", "amazing_pools"],
  },
  {
    title: "Yoga and Wellness Retreat, Pune",
    description: "A holistic retreat focused on yoga, meditation, and wellness.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1325&auto=format&fit=crop" },
    price: 4500,
    location: "Pune",
    country: "India",
    geometry: { type: "Point", coordinates: [73.8567, 18.5204] },
    features: ["countryside"],
  },
  {
    title: "Secluded Farmhouse, Punjab",
    description: "Experience authentic Punjabi hospitality in a large farmhouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1598454228432-a5483a75839d?q=80&w=1470&auto=format&fit=crop" },
    price: 3500,
    location: "Amritsar",
    country: "India",
    geometry: { type: "Point", coordinates: [74.8765, 31.634] },
    features: ["farms", "countryside"],
  },
  {
    title: "Designer Apartment in Chennai",
    description: "A beautifully designed apartment in a prime Chennai location.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1591088398332-8a7791972843?q=80&w=1374&auto=format&fit=crop" },
    price: 4000,
    location: "Chennai",
    country: "India",
    geometry: { type: "Point", coordinates: [80.2707, 13.0827] },
    features: ["iconic_cities"],
  },
  {
    title: "Cave Hotel in Badami",
    description: "A truly unique hotel built into the ancient caves of Badami.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1470&auto=format&fit=crop" },
    price: 3300,
    location: "Badami",
    country: "India",
    geometry: { type: "Point", coordinates: [75.683, 15.917] },
    features: ["tiny_homes", "off_the_grid"],
  },
  {
    title: "Colonial Club House, Darjeeling",
    description: "Stay in a historic club house with views of Kanchenjunga.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1596436889106-be35e843f974?q=80&w=1470&auto=format&fit=crop" },
    price: 5800,
    location: "Darjeeling",
    country: "India",
    geometry: { type: "Point", coordinates: [88.2636, 27.041] },
    features: ["mountains", "castles"],
  },
  {
    title: "Riverside Camp in Tirthan Valley",
    description: "Adventure camp by the river in the pristine Tirthan Valley.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?q=80&w=1374&auto=format&fit=crop" },
    price: 2600,
    location: "Tirthan Valley",
    country: "India",
    geometry: { type: "Point", coordinates: [77.341, 31.72] },
    features: ["mountains", "off_the_grid"],
  },
  {
    title: "Art Deco Apartment, South Mumbai",
    description: "Elegant apartment in a classic Art Deco building.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1471&auto=format&fit=crop" },
    price: 6200,
    location: "Mumbai",
    country: "India",
    geometry: { type: "Point", coordinates: [72.835, 18.922] },
    features: ["iconic_cities", "trending"],
  },
  {
    title: "Surfing School Villa, Varkala",
    description: "Stay right by the beach and learn to surf at this vibrant villa.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1567636788275-40c033c97352?q=80&w=1470&auto=format&fit=crop" },
    price: 3200,
    location: "Varkala",
    country: "India",
    geometry: { type: "Point", coordinates: [76.716, 8.737] },
    features: ["beachfront", "amazing_pools"],
  },
  {
    title: "Orchard Farm Stay, Himachal",
    description: "A lovely farm stay surrounded by apple orchards.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1576675784201-0e142b423952?q=80&w=1470&auto=format&fit=crop" },
    price: 2900,
    location: "Kotgarh",
    country: "India",
    geometry: { type: "Point", coordinates: [77.49, 31.32] },
    features: ["farms", "countryside"],
  },
  {
    title: "Bohemian Studio, Goa",
    description: "A quirky and colorful studio perfect for artists and dreamers.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1584132909910-942174a7a13c?q=80&w=1470&auto=format&fit=crop" },
    price: 2800,
    location: "Anjuna",
    country: "India",
    geometry: { type: "Point", coordinates: [73.74, 15.58] },
    features: ["private_rooms"],
  },
  {
    title: "Luxury Camp, Ranthambore",
    description: "Elegant tented camp near the Ranthambore Tiger Reserve.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1595514535965-2a86581a8b5e?q=80&w=1470&auto=format&fit=crop" },
    price: 9500,
    location: "Ranthambore",
    country: "India",
    geometry: { type: "Point", coordinates: [76.5, 26.01] },
    features: ["luxe", "off_the_grid"],
  },
  {
    title: "Sky High Apartment, Noida",
    description: "Modern apartment on a high floor with panoramic city views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?q=80&w=1374&auto=format&fit=crop" },
    price: 3800,
    location: "Noida",
    country: "India",
    geometry: { type: "Point", coordinates: [77.39, 28.53] },
    features: ["iconic_cities"],
  },
  {
    title: "Ganges View Room, Varanasi",
    description: "A simple room offering a profound view of the ghats and the Ganges.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587874551893-863b23d9b80b?q=80&w=1470&auto=format&fit=crop" },
    price: 2100,
    location: "Varanasi",
    country: "India",
    geometry: { type: "Point", coordinates: [82.97, 25.31] },
    features: ["iconic_cities", "trending"],
  },
  {
    title: "Bamboo Cottage, Shillong",
    description: "Eco-friendly cottage made of bamboo in the hills of Meghalaya.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1586611292717-f82841477647?q=80&w=1374&auto=format&fit=crop" },
    price: 3400,
    location: "Shillong",
    country: "India",
    geometry: { type: "Point", coordinates: [91.89, 25.57] },
    features: ["mountains", "cabins", "tiny_homes"],
  },
  {
    title: "Fort View Haveli, Jodhpur",
    description: "Traditional haveli with a stunning rooftop view of Mehrangarh Fort.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?q=80&w=1421&auto=format&fit=crop" },
    price: 4700,
    location: "Jodhpur",
    country: "India",
    geometry: { type: "Point", coordinates: [73.02, 26.23] },
    features: ["castles"],
  },
  {
    title: "Private Island Tent, Lakshadweep",
    description: "The ultimate escape: a single luxury tent on a private island.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?q=80&w=1470&auto=format&fit=crop" },
    price: 20000,
    location: "Agatti",
    country: "India",
    geometry: { type: "Point", coordinates: [72.19, 10.86] },
    features: ["beachfront", "luxe", "off_the_grid"],
  },
  {
    title: "Spiti Valley Homestay",
    description: "Experience the stark beauty and warm hospitality of Spiti Valley.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1588880331179-62b81a434da3?q=80&w=1470&auto=format&fit=crop" },
    price: 1800,
    location: "Kaza",
    country: "India",
    geometry: { type: "Point", coordinates: [78.07, 32.22] },
    features: ["mountains", "arctic", "private_rooms"],
  },
  {
    title: "Backwater Houseboat, Kumarakom",
    description: "A premium houseboat for a tranquil journey through the backwaters.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1470&auto=format&fit=crop" },
    price: 7000,
    location: "Kumarakom",
    country: "India",
    geometry: { type: "Point", coordinates: [76.43, 9.61] },
    features: ["boats"],
  },
  {
    title: "Heritage Hotel, Chettinad",
    description: "Stay in a grand mansion showcasing the unique architecture of Chettinad.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1594741149142-8a0429a3c95e?q=80&w=1470&auto=format&fit=crop" },
    price: 5500,
    location: "Karaikudi",
    country: "India",
    geometry: { type: "Point", coordinates: [78.77, 10.07] },
    features: ["castles", "countryside"],
  },
  {
    title: "A-Frame Cabin, near Manali",
    description: "A picturesque A-frame cabin nestled in an apple orchard.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1470&auto=format&fit=crop" },
    price: 4800,
    location: "Naggar",
    country: "India",
    geometry: { type: "Point", coordinates: [77.17, 32.11] },
    features: ["mountains", "cabins", "tiny_homes"],
  },
  {
    title: "Luxury Apartment, Hyderabad",
    description: "A high-end apartment in the upscale Jubilee Hills area.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560185893-a55de8537e49?q=80&w=1470&auto=format&fit=crop" },
    price: 5000,
    location: "Hyderabad",
    country: "India",
    geometry: { type: "Point", coordinates: [78.48, 17.38] },
    features: ["iconic_cities", "luxe"],
  },
  {
    title: "Coastal Bungalow, Alibaug",
    description: "A spacious bungalow with a large garden, a short walk from the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1471&auto=format&fit=crop" },
    price: 9000,
    location: "Alibaug",
    country: "India",
    geometry: { type: "Point", coordinates: [72.87, 18.64] },
    features: ["beachfront", "amazing_pools"],
  },
];

module.exports = { data: sampleListings };
